# Auto-assign configuration for Health Bridge
addReviewers: true
addAssignees: false

reviewers:
  - # Add your team members' GitHub usernames here
  # - "developer1"
  # - "developer2" 
  # - "tech-lead"

numberOfReviewers: 2

# Skip if PR is from these users (bots, etc.)
skipKeywords:
  - "dependabot"
  - "renovate"

# Assign based on file changes
fileBasedReviewers:
  # Backend changes
  "apps/backend/**":
    - # backend-specialist
  
  # Frontend changes  
  "apps/frontend/**":
    - # frontend-specialist
    
  # Database/Schema changes
  "**/*.schema.ts":
    - # database-specialist
    
  # Security/Auth changes
  "**/auth/**":
    - # security-specialist
    
  # CI/CD changes
  ".github/**":
    - # devops-specialist